---
filter:
  paths:
    - 'src/*'
    excluded_paths:
      - 'vendor/*'
      - 'tests/*'
      - 'build/*'
      - 'docs/*'
      - 'src/__.php'
  dependency_paths:
    - 'vendor/*'
coding_style:
  php: {  }
checks:
  php: true

tools:
  external_code_coverage:
    timeout: 600
  php_mess_detector: true
  php_code_sniffer: true
  sensiolabs_security_checker: true
  php_pdepend: true
  php_loc:
    enabled: true
    command: phploc
    excluded_dirs:
      - vendor
      - tests
      - build
      - docs
    sensiolabs_security_checker: true
  php_cpd:
    enabled: true
    excluded_dirs:
      - vendor
      - tests
      - build
      - docs

build:
  dependencies:
    override:
      - sudo composer selfupdate
      - sudo composer install-dev
  environment:
    timezone: UTC
    mysql: false
    postgresql: false
    redis: false
    php:
      version: 7.1, 7.2, 7.3,
  tests:
    override:
      - php-scrutinizer-run
