---
filter:
  paths:
  - src/*
  excluded_paths:
  - tests/*
  - src/__.php
  dependency_paths:
  - vendor/*
checks:
  php:
    verify_property_names: true
    verify_access_scope_valid: true
    variable_existence: true
    useless_calls: true
    unreachable_code: true
    unused_methods: true
    unused_parameters: true
    unused_properties: true
    unused_variables: true
    uppercase_constants: true
    use_statement_alias_conflict: true
    switch_fallthrough_commented: true
    single_namespace_per_use: true
    return_in_constructor: true
    return_doc_comments: true
    return_doc_comment_if_not_inferrable: true
    parameter_non_unique: true
    optional_parameters_at_the_end: true
    overriding_private_members: true
    no_unnecessary_final_modifier: true
    no_short_open_tag: true
    no_non_implemented_abstract_methods: true
    no_global_keyword: true
    no_goto: true
    no_exit: true
    newline_at_end_of_file: true
    line_length:
      max_length: '140'
    instanceof_class_exists: true
    avoid_closing_tag: true
    avoid_multiple_statements_on_same_line: true
    classes_in_camel_caps: true
    code_rating: true
    comparison_always_same_result: true
    avoid_duplicate_types: true
    check_method_contracts:
      verify_interface_like_constraints: true
      verify_documented_constraints: true
      verify_parent_constraints: true
    fix_line_ending: true
    overriding_parameter: true
    parameters_in_camelcaps: true

tools:
  external_code_coverage:
    timeout: 600
  php_mess_detector: true
  php_code_sniffer: true
  sensiolabs_security_checker: true
  php_pdepend: true
  php_loc:
    enabled: true
    excluded_dirs:
    - examples
    - tests
    - vendor
  php_cpd:
    enabled: true
    excluded_dirs:
    - examples
    - tests
    - vendor

build:
  dependencies:
      override:
        - sudo composer selfupdate
        - sudo composer install-dev
  environment:
    timezone: UTC
    mysql: false
    postgresql: false
    redis: false
    php:
      version: 7.1, 7.2, 7.3,
  tests:
    override:
    - php-scrutinizer-run
