dist: trusty
language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly


# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

## Cache composer
cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer self-update
  - travis_retry composer install-dev

script:
  #- vendor/bin/phpcs --standard=psr2 src/ todo enable it later
  - composer unit-cov
  - vendor/bin/phpstan analyse -l max src
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.xml

after_script:
  - |
    if [[ "$TRAVIS_PHP_VERSION" != 'hhvm' && "$TRAVIS_PHP_VERSION" != '7.0' ]]; then
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.xml
    fi

after_success:
  - bash <(curl -s https://codecov.io/bash)

